[package]
name = "gilo"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"

[target.'cfg(windows)'.dependencies]
windows-sys = { git = "https://github.com/microsoft/windows-rs.git", version = "0.100.0", features = [
    "setupapi",
    "hidsdi",
    "fileapi",
    "handleapi",
] }

[dependencies]
anyhow = "1.0.104"
tokio = { version = "1.53.1", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
    "sync",
    "signal",
] }
